---
- hosts: nodes
  remote_user: "{{ sudo_user }}"
  sudo: yes
  tasks:
    - name: Change default umask
      replace: dest=/etc/profile regexp='umask [0-7][0-7][0-7]$' replace='umask 0027'
    - name: Change current umask
      command: umask 027
    - name: Check whether /var is on it's own partition
      command: grep " /var " /etc/fstab
      always_run: True
      #ignore_errors: True
      changed_when: False
    - name: Check whether /var/log is on it's own partition
      command: grep " /var/log " /etc/fstab
      always_run: True
      #ignore_errors: True
      changed_when: False
    - name: Check whether /var/log/audit is on it's own partition
      command: grep " /var/log/audit " /etc/fstab
      always_run: True
      #ignore_errors: True
      changed_when: False
