- name: Ensure audit is Installed
  yum: 
    name=audit
- name: Enable auditd service
  service:
    name=auditd
    state=running
    enabled=yes
- name: Record attempts to alter time through adjtimex
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S adjtimex -k audit_time_rules'
    create=yes
    line='-a always,exit -F arch={{ item }} -S adjtimex -k audit_time_rules'
  notify: reload auditd
- name: Record attempts to alter time through settimeofday 
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S settimeofday -k audit_time_rules'
    create=yes
    line='-a always,exit -F arch={{ item }} -S settimeofday -k audit_time_rules'
  notify: reload auditd
- name: Record Attempts to Alter Time Through stime 
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S stime -k audit_time_rules'
    create=yes
    line='-a always,exit -F arch={{ item }} -S stime -k audit_time_rules'
  notify: reload auditd
- name: Record Attempts to Alter Time Through clock_settime
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S clock_settime -k audit_time_rules'
    create=yes
    line='-a always,exit -F arch={{ item }} -S clock_settime -k audit_time_rules'
  notify: reload auditd
- name: Record Attempts to Alter the localtime File
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/localtime -p wa -k audit_time_rules'
    create=yes
    line='-w /etc/localtime -p wa -k audit_time_rules'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - chmod
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - chown
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S chown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S chown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - fchmod
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S fchmod -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S fchmod -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - fchmodat
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - fchown
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S fchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S fchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - fchownat
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S fchownat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S fchownat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - fremovexattr
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - fsetxattr
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S fsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S fsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - lchown
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - lremovexattr
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S lremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S lremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - lsetxattr
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S lsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S lsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - removexattr
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S removexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S removexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify the System's Discretionary Access Controls - setxattr
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S setxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    create=yes
    line='-a always,exit -F arch={{ item }} -S setxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
  notify: reload auditd
- name: Record Events that Modify User/Group Information - /etc/group
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/group -p wa -k audit_rules_usergroup_modification'
    create=yes
    line='-w /etc/group -p wa -k audit_rules_usergroup_modification'
  notify: reload auditd
- name: Record Events that Modify User/Group Information - /etc/passwd
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/passwd -p wa -k audit_rules_usergroup_modification'
    create=yes
    line='-w /etc/passwd -p wa -k audit_rules_usergroup_modification'
  notify: reload auditd
- name: Record Events that Modify User/Group Information - /etc/gshadow
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/gshadow -p wa -k audit_rules_usergroup_modification'
    create=yes
    line='-w /etc/gshadow -p wa -k audit_rules_usergroup_modification'
  notify: reload auditd
- name: Record Events that Modify User/Group Information - /etc/shadow
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/shadow -p wa -k audit_rules_usergroup_modification'
    create=yes
    line='-w /etc/shadow -p wa -k audit_rules_usergroup_modification'
  notify: reload auditd
- name: Record Events that Modify User/Group Information - /etc/security/opasswd
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/security/opasswd -p wa -k audit_rules_usergroup_modification'
    create=yes
    line='-w /etc/security/opasswd -p wa -k audit_rules_usergroup_modification'
  notify: reload auditd
- name: Record Events that Modify the System's Network Environment - sethostname/setdomainname
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch=b64 -S sethostname -S setdomainname -k audit_rules_networkconfig_modification'
    create=yes
    line='-a always,exit -F arch=b64 -S sethostname -S setdomainname -k audit_rules_networkconfig_modification'
  notify: reload auditd
- name: Record Events that Modify the System's Network Environment - /etc/issue
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/issue -p wa -k audit_rules_networkconfig_modification'
    create=yes
    line='-w /etc/issue -p wa -k audit_rules_networkconfig_modification'
  notify: reload auditd
- name: Record Events that Modify the System's Network Environment - /etc/issue.net
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/issue.net -p wa -k audit_rules_networkconfig_modification'
    create=yes
    line='-w /etc/issue.net -p wa -k audit_rules_networkconfig_modification'
  notify: reload auditd
- name: Record Events that Modify the System's Network Environment - /etc/hosts
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/hosts -p wa -k audit_rules_networkconfig_modification'
    create=yes
    line='-w /etc/hosts -p wa -k audit_rules_networkconfig_modification'
  notify: reload auditd
- name: Record Events that Modify the System's Network Environment - /etc/sysconfig/network
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/sysconfig/network -p wa -k audit_rules_networkconfig_modification'
    create=yes
    line='-w /etc/sysconfig/network -p wa -k audit_rules_networkconfig_modification'
  notify: reload auditd
- name: Record Events that Modify the System's Mandatory Access Controls
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /etc/selinux/ -p wa -k MAC-policy'
    create=yes
    line='-w /etc/selinux/ -p wa -k MAC-policy'
  notify: reload auditd
- name: Ensure auditd Collects Unauthorized Access Attempts to Files (unsuccessful) - EACCESS
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S creat -S open -S openat -S open_by_handle_at -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access'
    create=yes
    line='-a always,exit -F arch={{ item }} -S creat -S open -S openat -S open_by_handle_at -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access'
  notify: reload auditd
- name: Ensure auditd Collects Unauthorized Access Attempts to Files (unsuccessful) - EPERM
  with_items: "{{ audit_arch }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch={{ item }} -S creat -S open -S openat -S open_by_handle_at -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access'
    create=yes
    line='-a always,exit -F arch={{ item }} -S creat -S open -S openat -S open_by_handle_at -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access'
  notify: reload auditd

- name: Find commands with setuid/setgid bit set on /
  shell: sudo find / -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
  register: find_result
- name: Ensure auditd Collects Information on the Use of Privileged Commands
  with_items: "{{ find_result.stdout_lines }}"
  lineinfile:
    dest="{{ audit_rules }}"
    regexp="-a always,exit -F path={{item}} -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
    create=yes
    line="-a always,exit -F path={{item}} -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
  notify: reload auditd

- name: Ensure auditd Collects Information on Exporting to Media (successful)
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k export'
    create=yes
    line='-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k export'
  notify: reload auditd

- name: Ensure auditd Collects File Deletion Events by User
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch=b64 -S rmdir -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete'
    create=yes
    line='-a always,exit -F arch=b64 -S rmdir -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete'
  notify: reload auditd
- name: Ensure auditd Collects System Administrator Actions
  lineinfile: 
    dest="{{ audit_rules  }}"
    regexp='-w /etc/sudoers -p wa -k actions'
    create=yes
    line='-w /etc/sudoers -p wa -k actions'
  notify: reload auditd

- name: Ensure auditd Collects Information on Kernel Module Loading and Unloading - insmod
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /usr/sbin/insmod -p x -k modules'
    create=yes
    line='-w /usr/sbin/insmod -p x -k modules'
  notify: reload auditd
- name: Ensure auditd Collects Information on Kernel Module Loading and Unloading - rmmod
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /usr/sbin/rmmod -p x -k modules'
    create=yes
    line='-w /usr/sbin/rmmod -p x -k modules'
  notify: reload auditd
- name: Ensure auditd Collects Information on Kernel Module Loading and Unloading - modprobe
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-w /usr/sbin/modprobe -p x -k modules'
    create=yes
    line='-w /usr/sbin/modprobe -p x -k modules'
  notify: reload auditd
- name: Ensure auditd Collects Information on Kernel Module Loading and Unloading - init_module/delete_module
  lineinfile:
    dest="{{ audit_rules }}"
    regexp='-a always,exit -F arch=b64 -S init_module -S delete_module -k modules'
    create=yes
    line='-a always,exit -F arch=b64 -S init_module -S delete_module -k modules'
  notify: reload auditd
