- name: Set Password Minimum Age
  lineinfile:
    dest=/etc/login.defs
    regexp="PASS_MIN_DAYS *[0-9]"
    state=present
    line="PASS_MIN_DAYS     1"
- name: Set Password Maximum Age
  lineinfile:
    dest=/etc/login.defs
    regexp="PASS_MAX_DAYS *[0-9]*"
    state=present
    line="PASS_MAX_DAYS     60"
- name: Modify the System Login Banner
  file:
    src=issue
    dest=/etc/issue
    group=root
    owner=root
    mode=644
- name: Set Password Minimum Length
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^minlen ='
    line="minlen = 15"
- name: Set Password Minimum Digit Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^dcredit ='
    line="dcredit = -1"
- name: Set Password Minimum Uppercase Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^ucredit ='
    line="ucredit = -1"
- name: Set Password Minimum Special Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='ocredit ='
    line="ocredit = -1"
- name: Set Password Minimum Lowercase Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^lcredit ='
    line="lcredit = -1"
- name: Set Password Strength Minimum Different Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^difok ='
    line="difok = 4"

