- name: Ensure Red Hat GPG Key Installed
  rpm_key:
    state=present
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  tags:
    - CCE-26506-6
    - SI-7
    - MA-1(b)
- name: Ensure gpgcheck Enabled In Main Yum Configuration
  replace:
    dest=/etc/yum.conf
    regexp='gpgcheck=0'
    replace='gpgcheck=1'
  tags:
    - CCE-26709-6
    - SI-7
    - MA-1(b)
- name: Find All Yum Repos
  shell: "/usr/bin/ls /etc/yum.repos.d/*.repo"
  register: yum_repos
  changed_when: False
  always_run: True
- name: Ensure gpgcheck Enabled For All Yum Package Repositories
  with_items: "{{ yum_repos.stdout_lines }}"
  replace:
    dest="{{ item }}"
    regexp='gpgcheck=0'
    replace='gpgcheck=1'
  tags:
    - CCE-26647-8
    - SI-7
    - MA-1(b)
