- name: Set Password Minimum Age
  lineinfile:
    dest=/etc/login.defs
    regexp="PASS_MIN_DAYS *[0-9]"
    state=present
    line="PASS_MIN_DAYS     1"
  tags:
    - CCE-27013-2
    - IA-5(f)
    - IA-5(1)(d)

- name: Set Password Maximum Age
  lineinfile:
    dest=/etc/login.defs
    regexp="PASS_MAX_DAYS *[0-9]*"
    state=present
    line="PASS_MAX_DAYS     60"
  tags:
    - CCE-26985-2
    - IA-5(f)
    - IA-5(g)
    - IA-5(1)(d)

- name: Set Password Warning Age
  lineinfile:
    dest=/etc/login.defs
    regexp="PASS_WARN_AGE *[0-9]"
    state=present
    line="PASS_WARN_AGE     7"
  tags:
    - CCE-26988-6
    - IA-5(f)

- name: Set Password Minimum Length
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^minlen ='
    line="minlen = 15"
  tags:
    - CCE-27002-5
    - IA-5(f)
    - IA-5(1)(a)
- name: Set Password Minimum Digit Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^dcredit ='
    line="dcredit = -1"
- name: Set Password Minimum Uppercase Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^ucredit ='
    line="ucredit = -1"
- name: Set Password Minimum Special Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='ocredit ='
    line="ocredit = -1"
- name: Set Password Minimum Lowercase Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^lcredit ='
    line="lcredit = -1"
- name: Set Password Strength Minimum Different Characters
  lineinfile:
    dest=/etc/security/pwquality.conf
    regexp='^difok ='
    line="difok = 4"

# Now set the password quality in the PAM modules

- name: Set Password Strength - /etc/pam.d/system-auth
  lineinfile:
    dest=/etc/pam.d/system-auth
    regexp='^password    requisite     pam_pwquality.so'
    line='password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=3'
    follow=yes
    backup=yes
  when: ansible_distribution_major_version == 7
  tags:
    - CCE-26374-9
    - CCE-26601-5
    - CCE-26631-2
    - CCE-26615-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)(a)

- name: Set Password Strength - /etc/pam.d/password-auth
  lineinfile:
    dest=/etc/pam.d/password-auth
    regexp='^password    requisite     pam_pwquality.so'
    line='password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=3'
    follow=yes
    backup=yes
  when: ansible_distribution_major_version == 7
  tags:
    - CCE-26374-9
    - CCE-26601-5
    - CCE-26631-2
    - CCE-26615-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)(a)

- name: Set Password Strength - /etc/pam.d/system-auth
  lineinfile:
    dest=/etc/pam.d/system-auth
    regexp='^password    requisite     pam_cracklib.so'
    line='password    requisite     pam_cracklib.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=3'
    follow=yes
    backup=yes
  when: ansible_distribution_major_version == 6
  tags:
    - CCE-26374-9
    - CCE-26601-5
    - CCE-26631-2
    - CCE-26615-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)(a)

- name: Set Password Strength - /etc/pam.d/password-auth
  lineinfile:
    dest=/etc/pam.d/password-auth
    regexp='^password    requisite     pam_cracklib.so'
    line='password    requisite     pam_cracklib.so try_first_pass local_users_only retry=3 authtok_type= dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 difok=4 maxrepeat=3'
    follow=yes
    backup=yes
  when: ansible_distribution_major_version == 6
  tags:
    - CCE-26374-9
    - CCE-26601-5
    - CCE-26631-2
    - CCE-26615-5
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)(a)





- name: Prevent Log In to Accounts With Empty Password - /etc/pam.d/system-auth
  replace:
    dest=/etc/pam.d/system-auth
    regexp=nullok
    follow=true
  tags:
    - CCE-27038-9
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)
- name: Prevent Log In to Accounts With Empty Password - /etc/pam.d/password-auth
  replace:
    dest=/etc/pam.d/password-auth
    regexp=nullok
    follow=true
  tags:
    - CCE-27038-9
    - IA-5(b)
    - IA-5(c)
    - IA-5(1)(a)
