#- name: Enable SELinux
- selinux: policy=targeted state=enforcing
  tags:
    - CCE-26969-6
    - CCE-26875-5
    - AC-3
    - AC-3(3)
    - AC-4
    - AC-6
    - AU-9
- name: Set SELinux to Enforcing
  command: /usr/sbin/setenforce 1
  when: ansible_selinux.mode == "permissive"
