- name: Enable SSH Warning Banner
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='Banner /etc/issue'
    line='Banner /etc/issue'
  notify:
  - reload ssh
- name: SSH Permit Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin "
    line="PermitRootLogin no"
  notify:
  - reload ssh
- name: SSH Permit Empty Passwords
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitEmptyPasswords "
    line="PermitEmptyPasswords no"
  notify:
    - reload ssh
- name: SSH Permit Password Authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication "
    line="PasswordAuthentication no"
  notify:
    - reload ssh
- name: Allow Only SSH Protocol 2
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^Protocol [0-9]"
    line="Protocol 2"
  notify:
    - reload ssh
  tags:
    - CCE-27072-8
    - AC-17(7)
    - IA-5(1)(c)

