- name: Install AIDE
  yum:
    name=aide
- name: Initialize AIDE
  command: /sbin/aide --init creates=/var/lib/aide/aide.db.new.gz
- name: Copy AIDE Database
  command: cp /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz creates=/var/lib/aide/aide.db.gz
- name: Schedule AIDE
  lineinfile:
    dest=/etc/crontab
    regexp=' root nice -19 /sbin/aide --check'
    line='{{ aide_minute }} {{ aide_hour }} {{ aide_day_of_month }} {{ aide_month }} {{ aide_day_of_week }} root nice -19 /sbin/aide --check'
